### ISSUE TITLE
Max & Min

### ISSUE THREAD

**Issue by YuBeccaFan** [sympy/scipy-2017-codegen-tutorial#27]
Why many languages likes js and R cannot be converted from Max & Min?
![image](https://user-images.githubusercontent.com/26391392/34532274-8e416144-f083-11e7-9442-3801e5b66a92.png)

**Comment by bjodah** [comment]
@AAmberFan that's probably an oversight in the printers, i.e. the methods `_print_Min`  and `_print_Max` need to be implemented for `JavascriptCodePrinter` in https://github.com/sympy/sympy/blob/master/sympy/printing/jscode.py (and the corresponding function in R).

I don't know if javascripts/R's Min/Max equivalents are "vectorized"? If not the need a solution similar to `_print_Min` in https://github.com/sympy/sympy/blob/master/sympy/printing/ccode.py, otherwise it's quite easy (see e.g. https://github.com/sympy/sympy/blob/master/sympy/printing/pycode.py).

Pull-requests against sympy/sympy is most welcome

**Comment by moorepants** [comment]
@AAmberFan please open an issue about this on the SymPy issue tracker: github.com/sympy/sympy/issues
