### ISSUE TITLE
binder has sympy 1.0

### ISSUE THREAD

**Issue by moorepants** [sympy/scipy-2017-codegen-tutorial#8]
Need to change to master.

**Comment by bjodah** [comment]
I was thinking about sympy@master to our anaconda channel, maybe under a dev label, don't know how to reference that in environment.yml though

**Comment by isuruf** [comment]
```
dependencies:
  - pip:
    - https://github.com/sympy/sympy/archive/master.tar.gz
```
or if you want a specific commit,
```
dependencies:
  - pip:
    - https://github.com/sympy/sympy/archive/7efbee85cf49d767a11de8344b2b99b2b2460769.tar.gz
```

**Comment by moorepants** [comment]
One of the packages in the env.yml seems to have a dependency on sympy, so removing sympy and adding this creates a double install of sympy.

**Comment by bjodah** [comment]
It's `python-symengine` -- I was actually thinking about just that.

**Comment by moorepants** [comment]
That's interesting. It's sort of circular to have sympy be a dependency of python-symengine.

**Comment by bjodah** [comment]
I was wrong, it's only the tests that actually require SymPy:
https://github.com/conda-forge/python-symengine-feedstock/blob/master/recipe/meta.yaml

**Comment by bjodah** [comment]
It is our own package... `scipy2017codegen`, so easily fixed. I'm on it.

**Comment by bjodah** [comment]
Now we have sympy@master in our binder environment. Thanks @isuruf!

I just realized that the Docker image that binder v2 comes with does not contain gcc. I'll add a separate `environment.yml` called `environment-binder.yml` which also lists `gcc` as a dependency. Because I think most people prefer relying on system provided compilers, right?
